# Multiple Linear Regression

## Importing the libraries

In [83]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [84]:
dataset=pd.read_csv('housing achintya.csv')
x=dataset.iloc[:,:5].values
y=dataset.iloc[:,-1].values

In [85]:
print(x)

[[7420    4    2    3    2]
 [8960    4    4    4    3]
 [9960    3    2    2    2]
 ...
 [3620    2    1    1    0]
 [2910    3    1    1    0]
 [3850    3    1    2    0]]


In [86]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in range(5,11):
  z=dataset.iloc[:,i].values
  z=le.fit_transform(z)
  z.reshape(545,1)
  x=np.column_stack((x,z))

In [87]:
print(x)

[[7420    4    2 ...    0    1    1]
 [8960    4    4 ...    0    1    0]
 [9960    3    2 ...    0    0    1]
 ...
 [3620    2    1 ...    0    0    0]
 [2910    3    1 ...    0    0    0]
 [3850    3    1 ...    0    0    0]]


In [88]:
v=dataset.iloc[:,-2].values
v=le.fit_transform(v)
v.reshape(len(v),1)
x=np.column_stack((x,v))

In [89]:
print(x)

[[7420    4    2 ...    1    1    0]
 [8960    4    4 ...    1    0    0]
 [9960    3    2 ...    0    1    1]
 ...
 [3620    2    1 ...    0    0    2]
 [2910    3    1 ...    0    0    0]
 [3850    3    1 ...    0    0    2]]


## Splitting the dataset into the Training set and Test set

In [90]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y, test_size=0.3,random_state=0)

## Training the Multiple Linear Regression model on the Training set

In [91]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(xtrain,ytrain)

LinearRegression()

## Predicting the Test set results

In [92]:
y_pred=regressor.predict(xtest)
print(np.concatenate((y_pred.reshape(len(y_pred),1),ytest.reshape(len(ytest),1)),1))

[[ 3984967.27379869  4585000.        ]
 [ 6244647.72325839  6083000.        ]
 [ 4429090.99016441  4007500.        ]
 [ 7327161.4857982   6930000.        ]
 [ 2884712.13473904  2940000.        ]
 [ 6980921.09080045  6195000.        ]
 [ 3292173.52565773  3535000.        ]
 [ 3158447.77360932  2940000.        ]
 [ 3546517.87305605  3500000.        ]
 [ 8271816.41131332  7980000.        ]
 [ 6618193.85905408  6755000.        ]
 [ 3751711.14944586  3990000.        ]
 [ 3753935.4031728   3150000.        ]
 [ 4583853.18651575  3290000.        ]
 [ 3966468.54850109  4130000.        ]
 [ 2025300.97229438  2660000.        ]
 [ 3979784.91637275  4410000.        ]
 [ 3615814.15041026  3710000.        ]
 [ 3199944.39530576  3360000.        ]
 [ 4676419.07100895  4270000.        ]
 [ 5824326.87304756  5005000.        ]
 [ 6417699.13990319  5383000.        ]
 [ 4677337.71216349  6440000.        ]
 [ 2728847.04375271  1890000.        ]
 [ 5377896.73425207  6125000.        ]
 [ 5707297.17442577  5460

Hence the final equation will be:
### y= 8.6*d1 -8.7*d2 +7.8*d3 +7.7*R&D +3.29*ADMIN +3.6*Market

## **Evaluating the Regression Model**

In [93]:
from sklearn.metrics import r2_score
r2_score(ytest,y_pred)*100

72.35015223200351